Allow to pass request options (for CORS scenarios) #76
Luxoft/gengen pull request #82
Opened 2021-10-29 13:07 UTC by jackkk94

feat: allow to pass request options

2021-11-01 13:26 UTC, sevaru requested changes

2021-11-01 13:26 UTC, sevaru commented on src/generators/angular/AngularServicesGenerator.ts
> +                    });
I think this logic belongs to method generation

2021-11-02 05:38 UTC, aleshchev requested changes

2021-11-02 05:38 UTC, aleshchev commented on src/bin.ts
> +    .option('--withRequestOptions')
You need describe it in Readme

2021-11-02 05:38 UTC, aleshchev commented on libs/download.service.ts
> +        options?: IAngularHttpRequestOptions,
is must be the latest

2021-11-02 05:38 UTC, aleshchev commented on src/generators/angular/AngularServicesGenerator.ts
> +                    : { name: BASE_SERVICE }, { name: HTTP_REQUEST_OPTIONS }
incorrect

2021-11-02 05:38 UTC, aleshchev commented on src/generators/angular/AngularServicesGenerator.ts
> +        const imports: ImportDeclarationStructure[] = [
why???

2021-11-02 05:38 UTC, aleshchev commented on src/generators/angular/AngularServicesMethodGenerator.ts
declare HTTP_REQUEST_OPTIONS here

2021-11-02 05:38 UTC, aleshchev commented on src/generators/angular/AngularServicesMethodGenerator.ts
> +    protected getMethodParameters(methodModel: IMethodModel): IMethodParameter[] {
wrong place for it

2021-11-02 05:38 UTC, aleshchev commented on src/generators/angular/AngularServicesMethodGenerator.ts
> +        if (!model.parameters.find(z => z.name === 'saveAs')) {
revert (). it's style

2021-11-02 12:55 UTC, jackkk94 commented on src/generators/angular/AngularServicesGenerator.ts
> +                    : { name: BASE_SERVICE }, { name: HTTP_REQUEST_OPTIONS }
why?

2021-11-03 06:41 UTC, sevaru requested changes

2021-11-03 06:41 UTC, sevaru commented on src/generators/angular/AngularServicesMethodGenerator.ts
> +                parameters: this.getMethodParameters(methodModel).map((p) => this.getParameterStatement(p)),
I guess we should separate our parameters from swagger and specific generation parameters (e.g. request options)

So I suggest solution like:

1) Method getMethodParameters(methodModel) that would return ParameterDeclarationStructure[]
2) getMethodParameters would map our methodModel.parameters
and adds option parameter as needed
Something like
```ts
public getMethodParameters(model) {
     const statements = model.parameters.map(x => this.getParameterStatement(x));

     if (this.options.withRequestOptions) {
          statements.push(this.getRequestOptionsParameter());
     }

     return statements;
}
```

that way we would not depend on the structure of our swagger based parameters.
and would not mutate model.parameters (which is external data for this service)

2021-11-03 06:41 UTC, sevaru commented on src/models/method-parameter/IMethodModel.ts
> +export type IMethodParameter = IPathParameter | IQueryParameter | IBodyParameter;
I think we should not name types with "I" and it should be MethodParameter

2021-11-03 13:31 UTC, sevaru commented on src/generators/angular/AngularServicesMethodGenerator.ts
> +        });
Maybe we could generate ParameterDeclarationStructure with method getParameterStatement?

There are alot of useless information like place, dtoType, isCollection, isModel

2021-11-03 13:31 UTC, sevaru commented on src/generators/angular/AngularServicesMethodGenerator.ts
> +        const parameter = first(model.parameters.filter((z) => z.name !== 'saveAs' && z.place === ParameterPlace.Body));
we do not use anything from MethodParameter except for the name
maybe type should be optionsParameter?: { name: string }

2021-11-08 06:47 UTC, sevaru commented on src/generators/angular/AngularServicesMethodGenerator.ts
> +            type: '$types.TypeOrUndefined<IAngularHttpRequestOptions>',
Lets make it just HTTP_REQUEST_OPTIONS

2021-11-09 06:57 UTC, sevaru approved these changes

2021-11-09 06:58 UTC, aleshchev approved these changes

2021-11-09 06:59 UTC, merged